### ISSUE TITLE
custom build_break_rules for max thresholds not being used

### ISSUE THREAD

**Issue by jooh-lee** [ShiftLeftSecurity/sast-scan#136]
I've set the below at the root of the git repo before scanning:
`{"build_break_rules":{"default":{"max_critical":0,"max_high":0,"max_medium":0}}}`

This isnt actually causing the build to break even though some of those limits are getting exceeded. In one of the builds, we the following result:
```
║ UNSPECIFIED │     0 │ ✅     ║
║ LOW         │     2 │ ✅     ║
║ MEDIUM      │     1 │ ✅     ║
║ HIGH        │     0 │ ✅     ║
║ CRITICAL    │     0 │ ✅     ║
```
Based off the custom build_break_rules the medium of 1 should have caused it to exit with a failure causing the ci build to break.

Doing this in aws codebuild, with the primary technology being nodejs with typescript. Im running the following commands at the root of the repo:
```
echo '{"build_break_rules":{"default":{"max_critical":0,"max_high":0,"max_medium":0}}}' >> .sastscanrc
docker run --rm -e "WORKSPACE=$PWD" -v $PWD:/app shiftleft/scan scan --build
```

**Comment by prabhu** [comment]
Build rules are currently limited to only SAST. I think the summary you have posted is for dependency scan results. My view is that just because there is a medium vulnerability in an oss dependency doesn't mean the build should break since the particular package may or may not be used in an attacker controlled path at all. We consider dependency scan results as an additional data to prioritize SAST results.

**Comment by jooh-lee** [comment]
are there plans to add an option to allow setting module thresholds? I can implement a local work around but would be nice if we can set the thresholds for modules as well

**Comment by prabhu** [comment]
Can you explain module threshold?

**Comment by jooh-lee** [comment]
oh sorry, i mean the dependency scan thresholds

**Comment by prabhu** [comment]
Sure happy to include this in the version 2 roadmap
