### ISSUE TITLE
scan using custom config file either by passing env or by mounting the file during docker run.

### ISSUE THREAD

**Issue by venky223** [ShiftLeftSecurity/sast-scan#69]
I'm unable to pass my custom config file through docker run to find the secrets. Is there a way that i can use my config file during docker run to find secrets.

docker run --rm -e "WORKSPACE=${PWD}" -e "CREDSCAN_DEPTH=0" -e "CREDSCAN_CONFIG=credscan-config.toml" -v $PWD:/app:cached shiftleft/sast-scan scan --src /app --type credscan --out_dir /app/reports

**Comment by prabhu** [comment]
Hi @venky223 

Please specify the full path to the config files including /app.

```bash
docker run --rm -e "WORKSPACE=${PWD}" -e "CREDSCAN_DEPTH=0" -e "CREDSCAN_CONFIG=/app/credscan-config.toml" -v $PWD:/app:cached shiftleft/sast-scan scan --src /app --type credscan --out_dir /app/reports
```

This is because /app is the directory inside the container image which is what the scan command would see.

It is also possible to customize the behaviour scan using a file called `.sastscanrc` as explained here: https://slscan.io/en/latest/integrations/tips/#config-file. An example for your use case is below:

```json
{
  "scan_type": "java,credscan,bash",
  "scan_tools_args_map": {
    "credscan": [
        "gitleaks",
        "--config=%(src)s/credscan-config.toml",
        "--depth=0",
        "--repo-path=%(src)s",
        "--redact",
        "--timeout=10m",
        "--report=%(report_fname_prefix)s.json",
        "--report-format=json",
    ]
  }
}
```

**Comment by prabhu** [comment]
Hi @venky223,

Did the above suggestions work?
